# CSE 252B: Computer Vision II, Winter 2019 – Assignment 2

### Instructor: Ben Ochoa

### Due: Wednesday, February 6, 2019, 11:59 PM

## Instructions
* Review the academic integrity and collaboration policies on the course website.
* This assignment must be completed individually.
* This assignment contains both math and programming problems.
* All solutions must be written in this notebook
* Math problems must be done in Markdown/LATEX. Remember to show work and describe your solution.
* Programming aspects of this assignment must be completed using Python in this notebook.
* Your code should be well written with sufficient comments to understand, but there is no need to write extra markdown to describe your solution if it is not explictly asked for.
* This notebook contains skeleton code, which should not be modified (This is important for standardization to facilate effeciant grading).
* You may use python packages for basic linear algebra, but you may not use packages that directly solve the problem. Ask the instructor if in doubt.
* You must submit this notebook exported as a pdf. You must also submit this notebook as an .ipynb file.
* Your code and results should remain inline in the pdf (Do not move your code to an appendix).
* You must submit both files (.pdf and .ipynb) on Gradescope. You must mark each problem on Gradescope in the pdf.
* It is highly recommended that you begin working on this assignment early.

## Problem 1 (Math): Line-plane intersection (5 points)
  The line in 3D defined by the join of the points $\boldsymbol{X}_1 = (X_1,
  Y_1, Z_1, T_1)^\top$ and $\boldsymbol{X}_2 = (X_2, Y_2, Z_2, T_2)^\top$
  can be represented as a Plucker matrix $\boldsymbol{L} = \boldsymbol{X}_1
  \boldsymbol{X}_2^\top - \boldsymbol{X}_2 \boldsymbol{X}_1^\top$ or pencil of points
  $\boldsymbol{X}(\lambda) = \lambda \boldsymbol{X}_1 + (1 - \lambda) \boldsymbol{X}_2$
  (i.e., $\boldsymbol{X}$ is a function of $\lambda$).  The line intersects
  the plane $\boldsymbol{\pi} = (a, b, c, d)^\top$ at the point
  $\boldsymbol{X}_{\boldsymbol{L}} = \boldsymbol{L} \boldsymbol{\pi}$ or
  $\boldsymbol{X}(\lambda_{\boldsymbol{\pi}})$, where $\lambda_{\boldsymbol{\pi}}$ is
  determined such that $\boldsymbol{X}(\lambda_{\boldsymbol{\pi}})^\top \boldsymbol{\pi} =
  0$ (i.e., $\boldsymbol{X}(\lambda_{\boldsymbol{\pi}})$ is the point on
  $\boldsymbol{\pi}$).  Show that $\boldsymbol{X}_{\boldsymbol{L}}$ is equal to
  $\boldsymbol{X}(\lambda_{\boldsymbol{\pi}})$ up to scale.

## Solution 1: 
Expand $\boldsymbol{X}(\lambda_{\boldsymbol{\pi}})^\top \boldsymbol{\pi} = 0$ with $\boldsymbol{X}(\lambda) = \lambda \boldsymbol{X}_1 + (1 - \lambda) \boldsymbol{X}_2$ and $\boldsymbol{\pi} = (a, b, c, d)^\top$: 

$$[\lambda_{\boldsymbol{\pi}}X_1 + (1-\lambda_{\boldsymbol{\pi}})X_2, 
\lambda_{\boldsymbol{\pi}}Y_1 + (1-\lambda_{\boldsymbol{\pi}})Y_2,  
\lambda_{\boldsymbol{\pi}}Z_1 + (1-\lambda_{\boldsymbol{\pi}})Z_2,  
\lambda_{\boldsymbol{\pi}}T_1 + (1-\lambda_{\boldsymbol{\pi}})T_2]^\top=0$$  

By solving the equation, we have  

$$\lambda_{\boldsymbol{\pi}}=\frac{-(aX_2 + bY_2 + cZ_2 + dT_2)}{(aX_1-aX_2)+(bY_1-bY_2)+(cZ_1+cZ_2)+(dT_1+T_2)} $$

Let $M = -[(aX_1-aX_2)+(bY_1-bY_2)+(cZ_1+cZ_2)+(dT_1+T_2)]$. Substitute $\lambda_{\boldsymbol{\pi}}$ with the equation above, we have:  

$$\boldsymbol{X}(\lambda_{\boldsymbol{\pi}})=
  \begin{bmatrix}
   b[(X_1Y_2-X_2Y_1)/M] + c[(X_1Z_2-X_2Z_1)/M] + d[(X_1T_2-X_2T_1)/M]\\
   a[(Y_1X_2-Y_2X_1)/M] + c[(Y_1Z_2-Y_2Z_1)/M] + d[(Y_1T_2-Y_2T_1)/M] \\
   a[(Z_1X_2-Z_2X_1)/M] + b[(Z_1Y_2-Z_2Y_1)/M] + d[(Z_1T_2-Z_2T_1)/M] \\
   a[(T_1X_2-T_2X_1)/M] + b[(T_1Y_2-T_2Y_1)/M] + c[(T_1Z_2-T_2Z_1)/M]
  \end{bmatrix}
$$

Substitute $\boldsymbol{L}$ with $\boldsymbol{L} = \boldsymbol{X}_1 \boldsymbol{X}_2^\top - \boldsymbol{X}_2 \boldsymbol{X}_1^\top$ in $\boldsymbol{X}_{\boldsymbol{L}} = \boldsymbol{L} \boldsymbol{\pi}$, expand with $\boldsymbol{X}_1 = (X_1, Y_1, Z_1, T_1)^\top$,  $\boldsymbol{X}_2 = (X_2, Y_2, Z_2, T_2)^\top$ and $\boldsymbol{\pi} = (a, b, c, d)^\top$:  

$$ \boldsymbol{X}_{\boldsymbol{L}} =
  \begin{bmatrix}
   b(X_1Y_2-X_2Y_1) + c(X_1Z_2-X_2Z_1) + d(X_1T_2-X_2T_1)\\
   a(Y_1X_2-Y_2X_1) + c(Y_1Z_2-Y_2Z_1) + d(Y_1T_2-Y_2T_1) \\
   a(Z_1X_2-Z_2X_1) + b(Z_1Y_2-Z_2Y_1) + d(Z_1T_2-Z_2T_1) \\
   a(T_1X_2-T_2X_1) + b(T_1Y_2-T_2Y_1) + c(T_1Z_2-T_2Z_1)
  \end{bmatrix}
$$

Therefore, $ \boldsymbol{X}_{\boldsymbol{L}} = \boldsymbol{X}(\lambda_{\boldsymbol{\pi}}) / M $. $\boldsymbol{X}_{\boldsymbol{L}}$ is equal to
  $\boldsymbol{X}(\lambda_{\boldsymbol{\pi}})$ up to scale.  
  
  

## Problem 2 (Math): Line-quadric intersection (5 points)
  In general, a line in 3D intersects a quadric $\boldsymbol{Q}$ at zero, one
  (if the line is tangent to the quadric), or two points.  If the
  pencil of points $\boldsymbol{X}(\lambda) = \lambda \boldsymbol{X}_1 + (1 -
  \lambda) \boldsymbol{X}_2$ represents a line in 3D, the (up to two) real
  roots of the quadratic polynomial $c_2 \lambda_{\boldsymbol{Q}}^2 + c_1
  \lambda_{\boldsymbol{Q}} + c_0 = 0$ are used to solve for the intersection
  point(s) $\boldsymbol{X}(\lambda_{\boldsymbol{Q}})$.  Show that $c_2 =
  \boldsymbol{X}_1^\top \boldsymbol{Q} \boldsymbol{X}_1 - 2 \boldsymbol{X}_1^\top \boldsymbol{Q}
  \boldsymbol{X}_2 + \boldsymbol{X}_2^\top \boldsymbol{Q} \boldsymbol{X}_2$, $c_1 = 2 (
  \boldsymbol{X}_1^\top \boldsymbol{Q} \boldsymbol{X}_2 - \boldsymbol{X}_2^\top \boldsymbol{Q}
  \boldsymbol{X}_2 )$, and $c_0 = \boldsymbol{X}_2^\top \boldsymbol{Q} \boldsymbol{X}_2$.

  In general, a line in 3D intersects a quadric $\boldsymbol{Q}$ at zero, one
  (if the line is tangent to the quadric), or two points.  If the
  pencil of points $\boldsymbol{X}(\lambda) = \lambda \boldsymbol{X}_1 + (1 -
  \lambda) \boldsymbol{X}_2$ represents a line in 3D, the (up to two) real
  roots of the quadratic polynomial $c_2 \lambda_{\boldsymbol{Q}}^2 + c_1
  \lambda_{\boldsymbol{Q}} + c_0 = 0$ are used to solve for the intersection
  point(s) $\boldsymbol{X}(\lambda_{\boldsymbol{Q}})$.  Show that $c_2 =
  \boldsymbol{X}_1^\top \boldsymbol{Q} \boldsymbol{X}_1 - 2 \boldsymbol{X}_1^\top \boldsymbol{Q}
  \boldsymbol{X}_2 + \boldsymbol{X}_2^\top \boldsymbol{Q} \boldsymbol{X}_2$, $c_1 = 2 (
  \boldsymbol{X}_1^\top \boldsymbol{Q} \boldsymbol{X}_2 - \boldsymbol{X}_2^\top \boldsymbol{Q}
  \boldsymbol{X}_2 )$, and $c_0 = \boldsymbol{X}_2^\top \boldsymbol{Q} \boldsymbol{X}_2$.
## Solution 2:
To find intersection points, we need to solve the equation: 

$$ \boldsymbol{X}(\lambda_{\boldsymbol{Q}})^\top \boldsymbol{Q} \boldsymbol{X}(\lambda_{\boldsymbol{Q}}) = 0$$

Substitute $ \boldsymbol{X}(\lambda_{\boldsymbol{Q}}) $ with $ \boldsymbol{X}(\lambda) = \lambda \boldsymbol{X}_1 + (1 - \lambda) \boldsymbol{X}_2 $:  
$$ [\lambda_{\boldsymbol{Q}} \boldsymbol{X}_1^\top + (1- \lambda_{\boldsymbol{Q}})\boldsymbol{X}_2^\top] \boldsymbol{Q} [\lambda_{\boldsymbol{Q}} \boldsymbol{X}_1 + (1- \lambda_{\boldsymbol{Q}})\boldsymbol{X}_2] = 0 $$

Expand the equation:  
$$ (\boldsymbol{X}_1^\top \boldsymbol{Q} \boldsymbol{X}_1 - 2 \boldsymbol{X}_1^\top \boldsymbol{Q} \boldsymbol{X}_2 + \boldsymbol{X}_2^\top \boldsymbol{Q} \boldsymbol{X}_2) \lambda_{\boldsymbol{Q}}^2 + 2 ( \boldsymbol{X}_1^\top \boldsymbol{Q} \boldsymbol{X}_2 - \boldsymbol{X}_2^\top \boldsymbol{Q} \boldsymbol{X}_2 ) \lambda_{\boldsymbol{Q}} + \boldsymbol{X}_2^\top \boldsymbol{Q} \boldsymbol{X}_2 = 0$$  

Therefore, we can conclude that $c_2 =
  \boldsymbol{X}_1^\top \boldsymbol{Q} \boldsymbol{X}_1 - 2 \boldsymbol{X}_1^\top \boldsymbol{Q}
  \boldsymbol{X}_2 + \boldsymbol{X}_2^\top \boldsymbol{Q} \boldsymbol{X}_2$, $c_1 = 2 (
  \boldsymbol{X}_1^\top \boldsymbol{Q} \boldsymbol{X}_2 - \boldsymbol{X}_2^\top \boldsymbol{Q}
  \boldsymbol{X}_2 )$, and $c_0 = \boldsymbol{X}_2^\top \boldsymbol{Q} \boldsymbol{X}_2$.  



## Problem 3 (Programming):  Linear Estimation of the Camera Projection Matrix (15 points)
  Download input data from the course website.  The file
  hw2_points3D.txt contains the coordinates of 50 scene points
  in 3D (each line of the file gives the $\tilde{X}_i$, $\tilde{Y}_i$,
  and $\tilde{Z}_i$ inhomogeneous coordinates of a point).  The file
  hw2_points2D.txt contains the coordinates of the 50
  corresponding image points in 2D (each line of the file gives the
  $\tilde{x}_i$ and $\tilde{y}_i$ inhomogeneous coordinates of a
  point).  The scene points have been randomly generated and projected
  to image points under a camera projection matrix (i.e., $\boldsymbol{x}_i
  = \boldsymbol{P} \boldsymbol{X}_i$), then noise has been added to the image point
  coordinates.

  Estimate the camera projection matrix $\boldsymbol{P}_\text{DLT}$ using the
  direct linear transformation (DLT) algorithm (with data
  normalization).  You must express $\boldsymbol{x}_i = \boldsymbol{P} \boldsymbol{X}_i$
  as $[\boldsymbol{x}_i]^\perp \boldsymbol{P} \boldsymbol{X}_i = \boldsymbol{0}$ (not
  $\boldsymbol{x}_i \times \boldsymbol{P} \boldsymbol{X}_i = \boldsymbol{0}$), where
  $[\boldsymbol{x}_i]^\perp \boldsymbol{x}_i = \boldsymbol{0}$, when forming the
  solution. Return
  $\boldsymbol{P}_\text{DLT}$, scaled such that
  $||\boldsymbol{P}_\text{DLT}||_\text{Fro} = 1$
  
  The following helper functions may be useful in your DLT function implementation.
  You are welcome to add any additional helper functions.

In [1]:
import numpy as np
import time

def Homogenize(x):
    # converts points from inhomogeneous to homogeneous coordinates
    return np.vstack((x,np.ones((1,x.shape[1]))))


def Dehomogenize(x):
    # converts points from homogeneous to inhomogeneous coordinates
    return x[:-1]/x[-1]


def Normalize(pts):
    # data normalization of n dimensional pts
    #
    # Input:
    #    pts - is in inhomogeneous coordinates
    # Outputs:
    #    pts - data normalized points
    #    T - corresponding transformation matrix
    """your code here"""
    n, m = pts.shape[0], pts.shape[1]
    u = [x.mean() for x in pts] # mean values of each dimensino
    d = [(np.std(x))**2 for x in pts] # deviation of each dimensino
    s = (n/sum(d))**0.5  # scale
    T = np.eye(n+1)
    T[:n, :n] = np.eye(n)*s
    T[:n,-1] = np.array(u)*(-1)*s  # Transform matrix
    pts = Homogenize(pts) 
    pts = np.array([T*np.mat(pts[:,i]).T for i in range(m)])
    pts = pts.reshape(m,n+1).T
    return pts, T

def projection(P, X):
    n = X.shape[1]
    x_hat = np.array([P*np.mat(X[:, i]).T for i in range(n)])  # projection
    x_hat = x_hat.reshape(x_hat.shape[:2]).T
    x_hat = Homogenize(Dehomogenize(x_hat))  # scale to x
    return x_hat

def ComputeCost(P, x, X):
    # Inputs:
    #    x - 2D inhomogeneous image points
    #    X - 3D inhomogeneous scene points
    #
    # Output:
    #    cost - Total reprojection error
    n = x.shape[1]
    covarx = np.eye(2*n)
    
    """your code here"""
    x = Homogenize(x)
    X = Homogenize(X)
    xx = projection(P,X)  # projection
    cost = sum([np.linalg.norm(xx[:, i] - x[:,i])**2 for i in range(n)]) # SSM
    return cost

def LeftNullVector(x):
    # compute left null of x
    e = np.array([1]+[0]*(x.shape[1]-1))
    V = [np.mat(a + np.linalg.norm(a)*e) if a[0]>0 \
         else np.mat(a - np.linalg.norm(a)*e) \
         for a in x]
    I = np.eye(x.shape[1])
    H = np.array([I-2*(v.T*v)/(v*v.T) for v in V])
    return H[:,1:,:]

In [2]:
def DLT(x, X, normalize=True):
    # Inputs:
    #    x - 2D inhomogeneous image points
    #    X - 3D inhomogeneous scene points
    #    normalize - if True, apply data normalization to x and X
    #
    # Output:
    #    P - the (3x4) DLT estimate of the camera projection matrix
    P = np.eye(3,4)+np.random.randn(3,4)/10
        
    # data normalization
    if normalize:
        x, T = Normalize(x)
        X, U = Normalize(X)
    else:
        x = Homogenize(x)
        X = Homogenize(X)
    
    """your code here"""
    
    x, X = x.T, X.T
    x_ = LeftNullVector(x)
    # A = [left_null(x) kron X]
    A = np.array([np.kron(x_[i],X[i]) for i in range(X.shape[0])])
    A = A.reshape((A.shape[0]*A.shape[1],1, A.shape[2]))
    A = A.reshape((A.shape[0], A.shape[2]))
    
    u, s, vh = np.linalg.svd(A,full_matrices=True)  # SVD
    p = vh[-1]
    P = np.mat(p.reshape((3,4)))
    
    # data denormalize
    if normalize:
        P = P/P[2,3]
        P = np.matmul(np.matmul(np.linalg.inv(T),P),U) #@ P @ U 
        P = P/np.linalg.norm(P)
    return P

def displayResults(P, x, X, title):
    print(title+' =')
    print (P/np.linalg.norm(P)*np.sign(P[-1,-1]))

# load the data
x=np.loadtxt('hw2_points2D.txt').T
X=np.loadtxt('hw2_points3D.txt').T


# compute the linear estimate without data normalization
print ('Running DLT without data normalization')
time_start=time.time()
P_DLT = DLT(x, X, normalize=False)
cost = ComputeCost(P_DLT, x, X)
time_total=time.time()-time_start
# display the results
print('took %f secs'%time_total)
print('Cost=%.9f'%cost)


# compute the linear estimate with data normalization
print ('Running DLT with data normalization')
time_start=time.time()
P_DLT = DLT(x, X, normalize=True)
cost = ComputeCost(P_DLT, x, X)
time_total=time.time()-time_start
# display the results
print('took %f secs'%time_total)
print('Cost=%.9f'%cost)

Running DLT without data normalization
took 0.078000 secs
Cost=97.053718839
Running DLT with data normalization
took 0.016000 secs
Cost=84.104680130


In [3]:
# Report your P_DLT value here!
displayResults(P_DLT, x, X, 'P_DLT')

P_DLT =
[[ 6.04350846e-03 -4.84282446e-03  8.82395315e-03  8.40441373e-01]
 [ 9.09666810e-03 -2.30374203e-03 -6.18060233e-03  5.41657305e-01]
 [ 5.00625470e-06  4.47558354e-06  2.55223773e-06  1.25160752e-03]]


## Problem 4 (Programming):  Nonlinear Estimation of the Camera Projection Matrix (30 points)
  Use $\boldsymbol{P}_\text{DLT}$ as an initial estimate to an iterative
  estimation method, specifically the Levenberg-Marquardt algorithm,
  to determine the Maximum Likelihood estimate of the camera
  projection matrix that minimizes the projection error.  You must
  parameterize the camera projection matrix as a parameterization of
  the homogeneous vector $\boldsymbol{p} = vec{(\boldsymbol{P}^\top)}$.  It is
  highly recommended to implement a parameterization of homogeneous
  vector method where the homogeneous vector is of arbitrary length,
  as this will be used in following assignments.
  
  Report the initial cost (i.e. cost at iteration 0) and the cost at the end
  of each successive iteration. Show the numerical values for the final 
  estimate of the camera projection matrix $\boldsymbol{P}_\text{LM}$, scaled
  such that $||\boldsymbol{P}_\text{LM}||_\text{Fro} = 1$.
  
  The following helper functions may be useful in your LM function implementation.
  You are welcome to add any additional helper functions.
  
  Hint: LM has its biggest cost reduction after the 1st iteration. You'll know if you 
  are implementing LM correctly if you experience this.

In [4]:
# Note that np.sinc is different than defined in class
def Sinc(x):
    # Returns a scalar valued sinc value
    """your code here"""
    if x==0: 
        y=1
    else: 
        y = np.sin(x)/x
    return y

def dSinc(x):
    # Returns a scalar valued sinc value
    """your code here"""
    if x==0: y=0
    else: y = np.cos(x)/x - np.sin(x)/(x**2)
    return y

def dx_dp(X, x, P):
    # Input: X - homogeneous 3D point, (4,)
    #        x - inhomogeneous 2D point, (2, )
    #        P - P matrix, (3,4)
    w = (np.mat(P[-1]) * np.mat(X).T)[0,0]
    J = np.zeros((2,12))
    J[0,:4] = X
    J[0, 8:] = (-1.0)*x[0]*X
    J[1,4:8] = X
    J[1, 8:] = (-1.0)*x[1]*X
    return J/float(w)

def dp_dpara(p):
    # Input: p - parameterized vector of P matrix, (11,)
    n = p.shape[0]
    J = np.zeros((n+1, n))
    p_norm = np.linalg.norm(p)
    b = Sinc(np.linalg.norm(p)/2.0)/2.0*p
    if p_norm==0:
        J[1:,:] = 0.5 * np.eye(n)
    else:
        J[0, :] = -0.5*b
        J[1:,:] = Sinc(p_norm/2.0)/2.0*np.eye(n) \
                + 1.0/(4.0*p_norm) * dSinc(p_norm/2.0) \
                * (np.mat(p).T * np.mat(p))
    return J

def Jacobian(P,p,X):
    # compute the jacobian matrix
    #
    # Input:
    #    P - 3x4 projection matrix
    #    p - 11x1 homogeneous parameterization of P
    #    X - 3n 3D inhomogeneous scene points
    # Output:
    #    J - 2nx11 jacobian matrix
    J = np.zeros((2*X.shape[1],p.shape[0]), dtype=np.float)
    
    """your code here"""
    X = Homogenize(X)
    n = X.shape[1]
    x = Dehomogenize(projection(P, X))
    x, X = x.T, X.T
    for i in range(n):
        J1 = dx_dp(X[i], x[i], P)
        J2 = dp_dpara(p)
        J[2*i:2*i+2,:] = np.dot(J1, J2)
    return J

def Parameterize(P):
    # wrapper function to interface with LM
    # takes all optimization variables and parameterizes all of them
    # in this case it is just P, but in future assignments it will
    # be more useful
    return ParameterizeHomog(P.reshape(-1,1))


def Deparameterize(p):
    # Deparameterize all optimization variables
    return DeParameterizeHomog(p).reshape(3,4)


def ParameterizeHomog(V):
    # Given a homogeneous vector V return its minimal parameterization
    """your code here"""
    v_hat = V[1:] * 2.0/(Sinc(np.arccos(V[0])))
    v_norm = np.linalg.norm(v_hat)
    if  v_norm> np.pi:
        v_hat = (1-(2.0*np.pi)/v_norm * np.ceil((v_norm-np.pi)/(2.0*np.pi)))*v_hat
    return v_hat


def DeParameterizeHomog(v):
    # Given a parameterized homogeneous vector return its deparameterization
    """your code here"""
    v_norm = np.linalg.norm(v)
    v_bar = (Sinc(v_norm/2.0)/2.0) * v
    v_bar = np.insert(v_bar, 0, np.cos(v_norm/2.0)) 
    return v_bar

def corvax(x_measure):
    # Input: x - measurement vector with shape (2n, 1)
    u = np.sum(x_measure)
    n = x_measure.shape[0]
    covar = np.mat((x_measure - u).T * (x_measure-u))/(n-1)
    return np.mat(np.eye(n))

def corvax_norm(cor, J):
    J = np.mat(J)
    return J*cor*J.T


In [5]:
def LM(P, x, X, max_iters, lam):
    # Input:
    #    P - initial estimate of P
    #    x - 2D inhomogeneous image points
    #    X - 3D inhomogeneous scene points
    #    max_iters - maximum number of iterations
    #    lam - lambda parameter
    # Output:
    #    P - Final P (3x4) obtained after convergence
    
    # data normalization
    x_inhomo, X_inhomo = x.copy(), X.copy()
    x, T = Normalize(x)
    X, U = Normalize(X)
    
    """your code here"""
    n = x.shape[1]
    cost = ComputeCost(P, x_inhomo, X_inhomo)  # initial cost
    P = np.matmul(np.matmul(T,P),np.linalg.inv(U))  # Normalize P matrix
    P = P/np.linalg.norm(P)
    
    xx = projection(P,X)  # initial projection results, (3, 50)
    x_measure = x[:2].T.reshape((n*2, 1))  # measurement vector, (2n, 1)
    x_hat = xx[:2].T.reshape((n*2, 1))  # initial estimate of measurement vector
    e = np.mat(x_measure - x_hat)  # initial epsilon, (2n, 1)
    cor = corvax(x_measure) # covariance matrix, (2n, 2n)
    cor_norm = corvax_norm(cor, T[0,0]*np.eye(cor.shape[0]))
    
    # transform P to an array with shape (sizeof(P),) for convenience
    p = np.squeeze(np.array(Parameterize(P))) # parameter vector,(11,)
    I = np.eye(11)
    
    # you may modify this so long as the cost is computed
    # at each iteration
    for i in range(max_iters): 
        J = np.mat(Jacobian(P, p, Dehomogenize(X))) # Jacobian, (2n, 11)
        J_normal = np.matmul(np.matmul(J.T, np.linalg.inv(cor_norm)),J) # (11, 11)
        J_target = np.dot(np.dot(J.T, np.linalg.inv(cor_norm)),e) # (11,1)
        delta = np.linalg.solve(J_normal+lam*I, J_target) # (11,1)
        
        pp = np.squeeze(p + np.array(delta.T)) # new parameter vector, (11,)
        PP = np.mat(Deparameterize(pp)) # new P matrix
        PP = PP/(PP[2,3])  # make the sign of PP to be +1
        PP_denorm = np.matmul(np.matmul(np.linalg.inv(T),PP),U) #denormalize new P matrix
        PP_denorm = PP_denorm/np.linalg.norm(PP_denorm)  
        cost_new = ComputeCost(PP_denorm, x_inhomo, X_inhomo)  # new_cost
            
        while(cost_new >= cost):
            lam*=10.0
            delta = np.linalg.solve(J_normal+lam*I, J_target) # (11,1)
            pp = np.squeeze(p + np.array(delta.T)) # new parameter vector, (11,)
            PP = np.mat(Deparameterize(pp)) # new P matrix
            PP = PP/(PP[2,3])  # make the sign of PP to be +1
            PP_denorm = np.matmul(np.matmul(np.linalg.inv(T),PP),U) #denormalize new P matrix
            PP_denorm = PP_denorm/np.linalg.norm(PP_denorm)
            cost_new = ComputeCost(PP_denorm, x_inhomo, X_inhomo)  # new_cost
            
        P, p = PP, pp
        xx = projection(P, X)
        x_hat = xx[:2].T.reshape((n*2, 1))
        e = np.mat(x_measure - x_hat)
        lam*=0.1
        print ('iter %03d Cost %.9f'%(i+1, cost_new))
        if(1-cost_new/cost<0.000000001): break
        cost = cost_new
        
    # data denormalization
    P = np.matmul(np.matmul(np.linalg.inv(T),P),U)
    return P

# LM hyperparameters
lam = 0.001
max_iters = 100

# Run LM initialized by DLT estimate with data normalization
print ('Running LM with data normalization')
print ('iter %03d Cost %.9f'%(0, cost))
time_start=time.time()
P_LM = LM(P_DLT, x, X, max_iters, lam)
time_total=time.time()-time_start
print('took %f secs'%time_total)


Running LM with data normalization
iter 000 Cost 84.104680130
iter 001 Cost 82.791336044
iter 002 Cost 82.790551563
iter 003 Cost 82.790327547
iter 004 Cost 82.790263575
iter 005 Cost 82.790245307
iter 006 Cost 82.790240091
iter 007 Cost 82.790238601
iter 008 Cost 82.790238175
iter 009 Cost 82.790238054
iter 010 Cost 82.790238019
took 0.093000 secs


In [6]:
# Report your P_LM final value here!
displayResults(P_LM, x, X, 'P_LM')

P_LM =
[[ 6.09434344e-03 -4.72647861e-03  8.79023487e-03  8.43642840e-01]
 [ 9.02017255e-03 -2.29290840e-03 -6.13330093e-03  5.36660251e-01]
 [ 4.99088599e-06  4.45205065e-06  2.53705044e-06  1.24348256e-03]]
